### ISSUE TITLE
MarkdownInput: Has a preview button but also a preview pane?

### ISSUE THREAD

**Issue by perlDreamer** [plainblack/ving#116]
Seems like with the preview pane that we don't need the "eyeball" (top-right)?  Are there options to disable the pane?

**Comment by rizen** [comment]
I don't see the eyeball that you're talking about. Can you screenshot it for me?

**Comment by rizen** [comment]
For example, here's the top of the bio in ving.
<img width="1665" alt="Screenshot 2024-04-22 at 7 49 02 PM" src="https://github.com/plainblack/ving/assets/170009/32f70cd0-73f4-43de-ae7f-89186dfbe0ac">

**Comment by perlDreamer** [comment]
<img width="1658" alt="Screenshot 2024-04-22 at 6 44 53 PM" src="https://github.com/plainblack/ving/assets/48078/744fe707-99c3-4014-961b-a0934fc4caf9">

**Comment by perlDreamer** [comment]
Profile/Bio from my MacBook, Chrome: 

<img width="1272" alt="Screenshot 2024-04-22 at 6 50 02 PM" src="https://github.com/plainblack/ving/assets/48078/2f5d2676-7a38-42c9-a59f-44509583a509">

**Comment by perlDreamer** [comment]
Actually, never mind.  Clicking on the eyeball hides the preview pane.
