### ISSUE TITLE
possible s3file upgrades

### ISSUE THREAD

**Issue by rizen** [plainblack/ving#120]
- maybe detect image properties with https://unjs.io/packages/image-meta
- switch from jimp to sharp https://sharp.pixelplumbing.com

**Comment by rizen** [comment]
image-meta supports very few file formats compared to image-size

**Comment by rizen** [comment]
sharp is faster than jimp, but jimp is working fine, so I'm not seeing a compelling reason to switch presently

**Comment by pi0** [comment]
let me know what format you find missing.

btw just you know i still have access to this repo but not see all notifs.

**Comment by rizen** [comment]
> let me know what format you find missing.

image-size has all these file formats: https://www.npmjs.com/package/image-size

But honestly, you would need to have more than what it has in order to make it a compelling reason to switch. I'm certainly not trying to create more work for you, as I know how busy you are already.

> btw just you know i still have access to this repo but not see all notifs.

I think you get the notifications because you have starred the repo.
