### ISSUE TITLE
[worker reload] [worker init] Invalid URL

### ISSUE THREAD

**Issue by devozs** [plainblack/ving#24]
First, thanks a lot for this repo.

`node --version && npm --version
`v18.12.0
9.6.5

After running
`npm run dev`

I am getting the following error:

> Nuxi 3.4.3                                                                                                                                                                                              
Nuxt 3.4.3 with Nitro 2.3.3                                                                                                                                                                             
 Local:    http://localhost:3000/ 
 Network:  http://10.0.0.7:3000/
 Network:  http://10.97.41.1:3000/
 Network:  http://172.17.0.1:3000/

ℹ Vite client warmed up in 2147ms                                                                                                                                                                       9:07:38 AM
✔ Nitro built in 1341 ms                                                                                                                                                                          nitro 9:07:39 AM

 ERROR  [worker reload] [worker init] Invalid URL                                                                                                                                                       9:07:40 AM

  at new NodeError (node:internal/errors:393:5)
  at URL.onParseError (node:internal/url:565:9)
  at new URL (node:internal/url:645:5)
  at .nuxt/dev/index.mjs:1463:18
  at ModuleJob.run (node:internal/modules/esm/module_job:193:25)
  at async Promise.all (index 0)
  at async ESMLoader.import (node:internal/modules/esm/loader:530:24)
  at async loadESM (node:internal/process/esm_loader:91:5)
  at async handleMainPromise (node:internal/modules/run_main:65:12)

Thanks.

**Comment by devozs** [comment]
my mistake.
Wrongly defined DB.
closing the issue

**Comment by rizen** [comment]
Wow. I didn't know anybody even looked at the repo. 

Just FYI, I'm still actively developing it. So please consider this an alpha software at this point.
