### ISSUE TITLE
detect fake emails

### ISSUE THREAD

**Issue by rizen** [plainblack/ving#27]
https://www.youtube.com/watch?v=goC5BdyCvms

**Comment by pi0** [comment]
Nice video. Quickly watched it and might missed it but consider for Google email services only, there are two more possible ways to have additional emails. If you have `user@gmail.com`, these also work and redirect to the same inbox:

- `user@googlemail.com`
- `u.ser@gmail.com`, `u.s.e.r@gmail.com`, etc

Also consider `+` notation in email is a way to have labeled emails to trace back spam sources and some users (including myself sometimes use it). They are not fake but with some pattern matching in SQL queries, we can check for duplicate emails skipping dot, domain alias an `+` part.

**Comment by rizen** [comment]
Thanks for the tips!

**Comment by rizen** [comment]
Given the feedback @pi0 I'm thinking the complexity and potential for error isn't worth the benefit in this case.
