### ISSUE TITLE
Error during npm install "Bus error 10"

### ISSUE THREAD

**Issue by perlDreamer** [plainblack/ving#65]
ares-5:fing colink$ npm install

> postinstall
> nuxt prepare

Bus error: 10

**Comment by rizen** [comment]
I have no idea what that is, but it's not a me problem. That sounds like a Nuxt problem. Did you try a second time?

**Comment by perlDreamer** [comment]
Ran this a 3rd time after deleting the node_modules directory and the packages.lock file and it passed.
