### ISSUE TITLE
Documentation: .env is not specific to Redis

### ISSUE THREAD

**Issue by perlDreamer** [plainblack/ving#66]
The way the docs are organized, it looks like ving's .env file is a sub-topic of redis.  It isn't, it's completely separate, so it should be at the same level.  The note about how to configure redis correctly should stay where it is though.

**Comment by rizen** [comment]
Are you referring to this page? https://plainblack.github.io/ving/env.html

**Comment by rizen** [comment]
Oh no you're referring to https://plainblack.github.io/ving/installation.html#create-your-env-file

**Comment by perlDreamer** [comment]
Correct.  On the installation page.

**Comment by rizen** [comment]
Ok, I believe this is fixed, but I'd like your confirmation. I've moved the .env to it's own section here:

https://plainblack.github.io/ving/installation#create-your-env-file

And then updated the other references to it in the Redis and MySQL sections.

Please close this if you believe it is fixed, or add a comment if you disagree.

**Comment by perlDreamer** [comment]
Nobody but you and I know what the "prod" and "dev" labels mean in that section of text.

**Comment by rizen** [comment]
Those are standard labels in the entire Node.js community, and I suspect elsewhere.
