### ISSUE TITLE
What steps are needed for one to run a database migration?

### ISSUE THREAD

**Issue by perlDreamer** [plainblack/ving#68]
Wing steps:

1. Bump database version number in lib/Project.pm
2. Make DB file changes in DB/Result/*.pm, or Role/Result/*.pm
3. Generate update files `wing db --prep --force`
4. Update the db `wing db --up`

Ving steps?

**Comment by rizen** [comment]
Ving steps:

- Make changes in `ving/schemas`
- Generate tables `./ving.mjs schema -t`
- Generate migration files .`/ving.mjs drizzle -p`
- Run migrations `./ving.mjs drizzle -u`
